pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

dependencyResolutionManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Architectury'
			url = 'https://maven.architectury.dev'
		}
		mavenCentral()
	}
}

include("wrapper")

def includeAllCompat = gradle.startParameter.projectProperties.get("airicraft.includeCompat") == "true"
def includeEvaluator = gradle.startParameter.projectProperties.get("airicraft.includeEvaluator") == "true"

if (includeEvaluator) {
	include("addons:evaluator")
}

if (includeAllCompat || gradle.startParameter.projectProperties.get("airicraft.includeReiCompat") == "true") {
	include("compat:rei")
}

if (includeAllCompat || gradle.startParameter.projectProperties.get("airicraft.includeJourneyMapCompat") == "true") {
	include("compat:journeymap")
}
