package ai.moeru.airicraft.agent.tasks;

public enum LedgerStepKind {
	COLLECT_RESOURCE,
	NAVIGATE_TO_POSITION,
	NAVIGATE_TO_BLOCK_KIND,
	MINE_BLOCKS,
	CRAFT_RECIPE,
	OPEN_CONTAINER,
	TRANSFER_ITEMS,
	PLACE_BLOCK,
	USE_BLOCK,
	DROP_ITEMS,
	SMELT_ITEMS,
	COLLECT_SMELTED_ITEMS,
	BREAK_BLOCKS,
	ATTACK_ENTITY,
	USE_ENTITY,
	ASK_USER,
	FINISH
}
