package ai.moeru.airicraft.agent.tasks;

public enum WorldTaskType {
	FOLLOW,
	NAVIGATE,
	MINE,
	CRAFT_RECIPE,
	DROP_ITEMS,
	SMELT_ITEMS,
	COLLECT_SMELTED_ITEMS,
	ATTACK_ENTITY,
	USE_ENTITY,
	PLACE_BLOCK,
	USE_BLOCK,
	BREAK_BLOCKS,
	RETURN_TO_SURFACE
}
