package ai.moeru.airicraft.agent.job;

public enum ActiveJobType {
	IDLE,
	FOLLOW_PLAYER,
	NAVIGATE_TO,
	MINE_BLOCKS,
	COLLECT_RESOURCE,
	CRAFT_RECIPE,
	DROP_ITEMS,
	SMELT_ITEMS,
	COLLECT_SMELTED_ITEMS,
	ATTACK_ENTITY,
	USE_ENTITY,
	ASK_USER
}
