package ai.moeru.airicraft.agent.job;

public enum ActiveJobType {
	IDLE,
	FOLLOW_PLAYER,
	NAVIGATE_TO,
	MINE_BLOCKS,
	ENSURE_BLOCKS_IN_INVENTORY,
	COLLECT_RESOURCE,
	CRAFT_RECIPE,
	DROP_ITEMS,
	SMELT_ITEMS,
	COLLECT_SMELTED_ITEMS,
	ATTACK_ENTITY,
	USE_ENTITY,
	PLACE_BLOCK,
	USE_BLOCK,
	BREAK_BLOCKS,
	RETURN_TO_SURFACE,
	ASK_USER
}
