plugins {
	id 'com.gradleup.shadow'
	id 'application'
}

group = project.maven_group
version = project.mod_version

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

application {
	mainClass = 'ai.moeru.airicraft.wrapper.AiricraftCliMain'
	applicationName = 'airicraft'
}

dependencies {
	implementation "info.picocli:picocli:4.7.6"
	implementation "com.fasterxml.jackson.core:jackson-databind:2.18.2"

	testImplementation platform("org.junit:junit-bom:5.11.4")
	testImplementation "org.junit.jupiter:junit-jupiter"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(CreateStartScripts).configureEach {
	applicationName = 'airicraft'
	doFirst {
		delete outputDir
	}
}

tasks.named('installDist') {
	doFirst {
		delete layout.buildDirectory.dir("install/${application.applicationName}")
	}
}

jar {
	manifest {
		attributes 'Main-Class': application.mainClass.get()
	}

	archiveClassifier = 'thin'
}

shadowJar {
	configurations = [project.configurations.runtimeClasspath]
	archiveClassifier = ''
}

build {
	dependsOn shadowJar
}
